spin_version = "1"
authors = ["Jason Washburn <jason.washburn@gmail.com>"]
description = "Advent of Spin Challenge"
name = "advent-of-spin-1"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "hello"
source = "hello/target/wasm32-wasi/release/hello.wasm"
[component.trigger]
route = "/hello"
[component.build]
command = "cargo build --target wasm32-wasi --release --manifest-path=./hello/Cargo.toml"
