spin_version = "1"
authors = ["Jason Washburn <jason.washburn@gmail.com>"]
description = "Advent of Spin Challenge 1"
name = "advent-of-spin-1"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "advent-of-spin-1"
source = "target/wasm32-wasi/release/advent_of_spin_1.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
